spring:
  application:
    name: cards
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:9001/"      
  profiles:
    active: "prod"      
server:
  port: 9004
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'  
  info:
    env:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0      
info:
 app:
  name: "cards"
  description: "JavaExpress Cards MS"
  version: "1.0.0"
  location: "Belgium"

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'  